trace-cmd: Fix use of uninitialized variable
Caught by clang's -Wsometimes-uninitialized and accepting the suggested
fix:

lib/trace-cmd/trace-input.c:4325:6: error: variable 'sec' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
        if (handle->file_state >= start_state) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/trace-cmd/trace-input.c:4336:6: note: uninitialized use occurs here
        if (sec)
            ^~~
lib/trace-cmd/trace-input.c:4325:2: note: remove the 'if' if its condition is always true
        if (handle->file_state >= start_state) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/trace-cmd/trace-input.c:4311:26: note: initialize the variable 'sec' to silence this warning
        struct file_section *sec;
                                ^
                                 = NULL

Link: https://lore.kernel.org/all/20220202214646.553872-1-irogers@google.com/

Reported-by: Ian Rogers <irogers@google.com>
Fixes: 616e204989c55 ("trace-cmd library: Use sections database when reading parts of the trace file")
Signed-off-by: Steven Rostedt (Google) <rostedt@goodmis.org>