trace-cmd: Set NO_PYTHON if python-dev package not found
The build fails with:

make[1]: `/work/git/trace-cmd.git/lib/trace-cmd/libtracecmd.a' is up to date.

    python-dev is not installed, not compiling python plugins

  COMPILE PLUGIN OBJ     plugin_python.o
Package python was not found in the pkg-config search path.
Perhaps you should add the directory containing `python.pc'
to the PKG_CONFIG_PATH environment variable
No package 'python' found
plugin_python.c:1:20: error: Python.h: No such file or directory
plugin_python.c: In function ‘load_plugin’:

Because even thought the python-dev package was found to be missing
the NO_PYTHON was not set, and that is used to determine building
the python plugin.

Fixes: c7d73430e505 ("trace-cmd: Make the build to tell when python-dev is missing")
Signed-off-by: Steven Rostedt (VMware) <rostedt@goodmis.org>