trace-cmd: link trace-record in ctracecmd.so
Commit b1e9220819eb (trace-cmd: Report stats for all instances) moved
tracecmd_stat_cpu() from trace-recorder.c to trace-record.c.  This
makes import ctracecmd fail in tracecmd.py:

$ python tracecmd.py
Traceback (most recent call last):
  File "tracecmd.py", line 22, in <module>
    from ctracecmd import *
ImportError: ctracecmd.so: undefined symbol: tracecmd_stat_cpu

Link trace-record in ctracecmd.so to add back the required symbol.

Link: http://lkml.kernel.org/p/1408116698-23033-1-git-send-email-javi.merino@arm.com

Signed-off-by: Javi Merino <javi.merino@arm.com>
Signed-off-by: Steven Rostedt <rostedt@goodmis.org>